### ISSUE TITLE
Issue for  keyboards repository but there isn't issue tab

### ISSUE THREAD

**Issue by UltimateWishub** [geezorg/Xliterator#45]
I need help to add a new line to the zema milikit because sometimes there are more than 1 way of saying the zema and it is shown above the 1st milikit
![image](https://user-images.githubusercontent.com/60529992/137596002-3d30979e-31a4-4865-a16d-f02db78cf897.png)

**Comment by UltimateWishub** [comment]
Thank you!

**Comment by dyacob** [comment]
Glad that you are trying to type zaima miliket, was it at the Keyman site where you tried to report an issue?  I am planning to add more documentation and examples to the GFF Ge'ez Keyboard on how to type miliket.  The  “Geʾez Manuscript Zemen” will also be included with the keyboard.  But it may not be until December or January.  Let me know what type of examples would be most helpful to have.

**Comment by dyacob** [comment]
I'm assuming that you are using Microsoft Word, if so, notice in the Phonetic Guide dialog that there is a "Font" menu where you can set the miliket font different from the font of the base text.  I've attached a page with some sample text that is shown in the screenshot.  Some of the symbols do not look clear in the dialog preview.  They may also not look good on screen unless you zoom a lot, when printed, they should look fine.

![GeezManuscriptZemen-Miliket-Example](https://user-images.githubusercontent.com/8098333/137600842-3f6f1fd4-79e3-4c52-8c05-990a6117749e.PNG)


[Zaima-Miliket-Sample.docx](https://github.com/geezorg/Xliterator/files/7358209/Zaima-Miliket-Sample.docx)

**Comment by UltimateWishub** [comment]
ok thanks

**Comment by dyacob** [comment]
One more note that I forgot... Sometimes (probably most of the time) with Word it will not recognize a font addition until Word is restarted.  Actually, you may have to shutdown all Office products, then re-open Word for it to find a new font or change of a font.
